# Generated by Django 4.2.6 on 2023-11-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='chat_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True, verbose_name='номер телефона'),
        ),
    ]
