# Generated by Django 4.2.6 on 2023-11-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_chat_id_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
