# Generated by Django 4.2.6 on 2023-11-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='время выполения привычки')),
                ('action', models.CharField(blank=True, max_length=250, null=True, verbose_name='действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='Привычка приятная?')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='действие')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
