# Generated by Django 4.2.6 on 2023-11-13 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('is_public',), 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Признак публичности'),
        ),
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('DAILY', 'каждый день'), ('WEEKLY', 'раз в неделю')], default='DAILY', max_length=12, verbose_name='Периодичность выполнения'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete',
            field=models.TimeField(default=datetime.time(0, 2), verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='время выполения привычки'),
        ),
    ]
