# Generated by Django 4.2.6 on 2023-11-14 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0002_alter_habit_options_habit_is_public_habit_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('time',), 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='next_reminder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего напоминания'),
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время и дата начала'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
