# Generated by Django 4.2.6 on 2023-11-14 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_options_habit_next_reminder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата начала'),
        ),
    ]
