# Generated by Django 4.2.6 on 2023-11-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(verbose_name='Время и дата начала'),
        ),
    ]
