# Generated by Django 4.2.6 on 2023-11-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('is_public',), 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
    ]
