# Generated by Django 4.2.6 on 2023-11-14 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_options_remove_habit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('time',), 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата начала'),
        ),
    ]
