# Generated by Django 4.2.6 on 2023-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_options_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.SmallIntegerField(default=7, verbose_name='Периодичность выполнения'),
        ),
    ]
